export const RETRIEVE_LINKS = 'RETRIEVE_LINKS'
export const RETRIEVE_LINK = 'RETRIEVE_LINK'
export const FUNCTION_GET_LINKS = 'FUNCTION_GET_LINKS'

export const RETRIEVE_TUTORIAIS = 'RETRIEVE_TUTORIAIS'
export const RETRIEVE_TUTORIAL = 'RETRIEVE_TUTORIAL'
export const FUNCTION_GET_TUTORIAIS = 'FUNCTION_GET_TUTORIAIS'
export const FORWARD_PAGE = 'FORWARD_PAGE'
export const BACKWARD_PAGE = 'BACKWARD_PAGE'
export const SET_PAGE = 'SET_PAGE'


