export const RETRIEVE_LINKS = 'RETRIEVE_LINKS'
export const RETRIEVE_LINK = 'RETRIEVE_LINK'

export const RETRIEVE_TUTORIAIS = 'RETRIEVE_TUTORIAIS'
export const RETRIEVE_TUTORIAL = 'RETRIEVE_TUTORIAL'
